name: Homelab Deployment
on: [push]
jobs:
  Start-Cargo-Server:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Check out repo
        run: stat repo || git clone git@github.com:dowlandaiello/tzchat repo
      - name: Check systemd configuration
        run: stat $HOME/.local/share/systemd/user/tzchat.service || repo/.create_systemd.sh
      - name: Build and start actix server
        run: |
          cd repo
          $HOME/.cargo/bin/cargo check
          systemctl --user restart tzhschat
