name: Homelab Deployment
on: [push]
jobs:
  Start-Cargo-Server:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Check out repo
        run: (stat repo && pushd repo && git pull origin master && popd) || git clone git@github.com:dowlandaiello/tzchat repo
      - name: Check systemd configuration
        run: pushd repo && ./.create_systemd.sh && popd
      - name: Build and start actix server
        run: |
          cd repo
          $HOME/.cargo/bin/cargo build
          systemctl --user daemon-reload
          systemctl --user restart tzchat
